name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^14.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
